---
galaxy_info:
  author: sky-joker
  description: Build a nested ESXi environment.
  company: myCompany.Dotcom
  license: MIT
  min_ansible_version: 2.9
  platforms:
    - name: EL
      versions:
        - 7
        - 8
  galaxy_tags:
    - vmware
dependencies: []